# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=50)),
                ('Timestamp', models.DateTimeField()),
                ('Tags', models.CharField(max_length=150)),
                ('Text', models.TextField()),
                ('Link', models.CharField(max_length=100)),
                ('ImageLink', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSourceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTagMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='SourceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Tags')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User')),
            ],
        ),
        migrations.AddField(
            model_name='sourceprofile',
            name='SourceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Sources'),
        ),
        migrations.AddField(
            model_name='sourceprofile',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User'),
        ),
        migrations.AddField(
            model_name='articletagmap',
            name='TagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Tags'),
        ),
        migrations.AddField(
            model_name='articlesourcemap',
            name='SourceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Sources'),
        ),
    ]
