# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170419_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Link',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
