# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=50)),
                ('Timestamp', models.DateTimeField()),
                ('Tags', models.CharField(max_length=150)),
                ('Text', models.TextField()),
                ('Link', models.CharField(max_length=100, unique=True)),
                ('ImageLink', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTagMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='SourceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tags')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sourceprofile',
            name='SourceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Sources'),
        ),
        migrations.AddField(
            model_name='sourceprofile',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articletagmap',
            name='TagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tags'),
        ),
        migrations.AddField(
            model_name='articles',
            name='SourceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Sources'),
        ),
    ]
