# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='ImageLink',
            new_name='imageLink',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='SourceID',
            new_name='sourceID',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='articletagmap',
            old_name='ArticleID',
            new_name='articleID',
        ),
        migrations.RenameField(
            model_name='articletagmap',
            old_name='TagID',
            new_name='tagID',
        ),
        migrations.RenameField(
            model_name='sourceprofile',
            old_name='SourceID',
            new_name='sourceID',
        ),
        migrations.RenameField(
            model_name='sourceprofile',
            old_name='UserID',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='sources',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tagsprofile',
            old_name='TagID',
            new_name='tagID',
        ),
        migrations.RenameField(
            model_name='tagsprofile',
            old_name='UserID',
            new_name='userID',
        ),
    ]
