# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170421_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'artykuł', 'verbose_name_plural': 'artykuły'},
        ),
        migrations.AlterModelOptions(
            name='articletagmap',
            options={'verbose_name': 'artykuł-tag', 'verbose_name_plural': 'artykuły-tagi'},
        ),
        migrations.AlterModelOptions(
            name='sourceprofile',
            options={'verbose_name': 'użytkownik-źródło', 'verbose_name_plural': 'użytkownicy-źródła'},
        ),
        migrations.AlterModelOptions(
            name='sources',
            options={'verbose_name': 'źródło', 'verbose_name_plural': 'źródła'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tagi'},
        ),
        migrations.AlterModelOptions(
            name='tagsprofile',
            options={'verbose_name': 'użytkownik-tag', 'verbose_name_plural': 'użytkownicy-tagi'},
        ),
    ]
