# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_auto_20170528_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(max_length=150)),
                ('sources_list', models.TextField()),
                ('tags_list', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil wyszukiwania',
                'verbose_name_plural': 'profile wyszukiwania',
            },
        ),
        migrations.RemoveField(
            model_name='sourceprofile',
            name='sourceID',
        ),
        migrations.RemoveField(
            model_name='sourceprofile',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='tagsprofile',
            name='tagID',
        ),
        migrations.RemoveField(
            model_name='tagsprofile',
            name='userID',
        ),
        migrations.DeleteModel(
            name='SourceProfile',
        ),
        migrations.DeleteModel(
            name='TagsProfile',
        ),
    ]
